language: python
python:
  - "3.5"
  - "3.6"

install:
  - make install

script:
  - make lint
  - make test

deploy:
  provider: pypi
  user: solumilken
  password:
    secure: dFRASkM+gXpPqqbWL8PS2XAbyutbJnU8z5rk88+J2XJhn5IyXkn6wBycXtkhgkuqT34HfIZrcTFBYgrsGu44hTXHwvQwFFHtHkU8tqLaa2gnvODlWPkG6AjmgzyrR/yAvpHpYEea13xC3biD3TGa1Do9aFbDsdfnni1Cpjd4dbcY6c2IoHp0V047tAIaq9agqeCvONVxbPbfuzvc24QbSzfyr2brJdruFR02baqZXnAmdMomLvsY1jzoUhp4k/qU449lfT1p0ITVdLyrCFxqK1A1DyvKcHRv3Shm+MeNbn3Y/AIVjfN71KQaGdsknUFmPjFbBfJPQuzSwRldGm1DaLm8a5A4WLmRmG2ZkMZWrlNWXsc/GbIFxuwA1llJruHgSf6zzwpWMECiDPh3LGo0K21f2nWSgmaJBMPIeLhxHmQ2uEUUkc7EKukdiF1X4ib024FoLvBkBfII/d1qRi6pPse7lKQRC5nILSynBAMaOwTESZnd9BGShpyH7/VPIzEI58ic/q9c/JgDQVXWp55KetSTXv9xdx4ACZ0KIalQlDJKX7dtuNIZKK9mQ8CM4hgdRxGd4Sb1wX3PTSlQEyeBXRjqu4+hjgfqgBWxNCb+9s99/3UQE1O0us6NBencIxd44exR7T8kkHdiI3Q17dxu43mn/8XDnwkiGQUz0K9GYko=
    distributions: sdist
  skip_upload_docs: true
  skip_cleanup: true
  on:
    tags: true
  python: 3.5
