language: python
python:
- '3.5'
- '3.6'
install:
- make install
script:
- make lint
- make test
deploy:
  provider: pypi
  user: solumilken
  password:
    secure: 0Opwlmv6qK1uyW2u3sE5rbdNiopeFTvG8kKAFZS3b5joRpiCKRdRGPYPIfCf1l8S5SeXq6INt6HIHcxyNDsIB1ejHYYJu33wL9tK1mUekivlEXibdEDaN3/qNfT9dZDWm/4tUFrFvHGhB6krJjIToUYsJvM3tYBSX6uCgfxFrpr6GsLNrxs/nIzy2aCD9MMReQ89iC3IQoWkTuTIbGnuj7eWEQpbhjLmBIrwJwnh5zcjdrR9PAzWakOX4bMeVa89nQiaL16icTaHthCQrLuyCP7lQ2tlh7rO4yT+UF4qLynWFAEYEQL3mvx+I/bNpKaRvHy26ZgkTLsd5mJsntbohDYN0Ydyx6nXTzuAMsElumMdVYizJghh8+/x9CfbF+CqK6qQ/UqL10OjFUinTNcYUi9jzt2hsGnno9eDjzVtlQmo4i+N3MQRciTWbQawWM7VXmjT7rGI18Zc4zp4/Y9qEZG18QZzaDPexXFOpJU7pWt07658jMHwGqmQJiyIWXTKjBq4IWxIw/s7VmE5R0ElqgCL6spwC3ErHzJvvX1XhrU98lDqyk1VWQxtRl/jyA3OLKnInou92jLPH3M0iAriKlttHxEacFEj0rsaaYDYtLwvyIiWFNdaATraIBaH8cQeoMJH4HmNTCAQFFRUW1B1/Ss2XCgEuUpLaPQaGrpNyNo=
  skip_upload_docs: true
  skip_cleanup: true
  on:
    tags: true
  python: 3.5
